version: 1

formatters:
  file_format:
    format: "%(asctime)s | %(name)s | %(module)s | %(funcName)s | %(levelname)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: file_format
    filename: log/record
    encoding: utf-8

loggers:
  file_logger:
    handlers: [file_handler]
    level: INFO
